# Generated by Django 2.0.5 on 2018-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questbase',
            name='bought',
        ),
        migrations.AddField(
            model_name='questbase',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиумная'),
        ),
    ]
