# Generated by Django 2.0.5 on 2018-06-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0006_auto_20180603_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerordering',
            options={'ordering': ('order_number',), 'verbose_name': 'Элемент по порядку', 'verbose_name_plural': 'Элементы по порядку'},
        ),
    ]
